name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: Restore
        run: dotnet restore
        working-directory: src/AssetControl.SmallBiz
      - name: Build
        run: dotnet build --no-restore -c Release
        working-directory: src/AssetControl.SmallBiz
      - name: Run tests (if any)
        run: |
          if [ -d "tests" ]; then dotnet test --no-build -c Release; else echo "No tests"; fi
        working-directory: src/AssetControl.SmallBiz
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: Restore
        run: dotnet restore ./
      - name: Build
        run: dotnet build --no-restore -c Release
      - name: Run tests (if any)
        run: |
          if [ -d "tests" ]; then dotnet test --no-build -c Release; else echo "No tests"; fi
